"""empty message

Revision ID: f63e8edef2c2
Revises: 7ec66ee0ca9a
Create Date: 2024-08-11 20:42:39.556647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63e8edef2c2'
down_revision = '7ec66ee0ca9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musicbrainz_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('musicbrainz_id')

    # ### end Alembic commands ###
